src/objects/CP_Chatter_Pulse__c.object
<CustomObject>
    <description>Reporting statistics for Chatter Pulse</description>
    <fields>
        <fullName>Chatter_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Chatter User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>CP_Chatter_Pulse</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Related_Record__c</fullName>
        <label>Related Record</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Date__c</fullName>
        <description>Reporting date for Chatter statistics</description>
        <label>Reporting Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Update_Type__c</fullName>
        <label>Update Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Chatter Pulse</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>CP: Chatter Pulse ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Chatter Pulse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ChatterPulseUser.cls
global class ChatterPulseUser {  
	public static void PulseAdd(Set<Id> userIds) {
		List<User> user = [select Id, CurrentStatus from user where Id IN :userIds];
		//Create a list to store the update tracker
		List<CP_Chatter_Pulse__c> listChatterPulse = new List<CP_Chatter_Pulse__c>();
		for (User usr : User) {
			//Create a ParentID and something similar to the FeedItem type used in the FeedItem/FeedComment triggers
			String userId = String.valueOf(usr.Id);
			String postType = 'Status: StatusCleared'; //Make this look similar to the Feed and Comment triggers
			if(usr.CurrentStatus != NULL) {
				postType = 'Status: StatusUpdate';
			}
				listChatterPulse.add(new CP_Chatter_Pulse__c(Chatter_User__c = usr.Id ,
				Reporting_Date__c = Date.today(), Update_Type__c = postType, Related_Record__c = userId ));
			}
		insert listChatterPulse;
	}
}